# Generated by Django 4.1.7 on 2024-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0006_remove_orderitem_price_product_price_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/product/'),
            preserve_default=False,
        ),
    ]
