# Generated by Django 4.1.7 on 2024-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0007_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('shippingaddress', models.CharField(max_length=100)),
                ('billingaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
