# Generated by Django 4.1.7 on 2024-05-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0008_ordernew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordernew',
            old_name='billingaddress',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='ordernew',
            old_name='shippingaddress',
            new_name='shipping_address',
        ),
    ]
